Update to new version of standard EditorConfig
Before this change, if you ran “pre-commit run --all”, then the
repo-style-checker pre-commit hook would give you this error:

> ERROR: .editorconfig doesn’t contain the standard .editorconfig file.
> Fixing…

This change fixes that error.